### PR TITLE
Display ToC of texinfo generated html in fixed sidebar

### PR DESCRIPTION
**Pull request by afh**
I find the table of contents (ToC) on the html pages generated by texinfo a bit "too classic" as jumping back and fourth from the ToC on top of the page and the manual using the inline navigational links seems rather disruptive.

Fiddling around with CSS I found a CSS only solution that places the ToC in a fixed sidebar to the left of the manual. This works well enough for me on macOS using Safari, Chrome, and Mullvad Browser that a PR, this PR, seems in order.

**NOTA BENE:** This PR stacks on top of #73, the only actual relevant changes for this PR are in commit 41d196f52bcd860a46451d6112007f64f65bd98b.

For a live preview visit: http://projects.surryhill.net/ledger/ledger3.html

image

### CODE REVIEW

**Comment by kljohann** [comment]
Looks fine on devices with larger screens but FWIW the menu takes up too much space on small/narrow screens (e.g., mobile phones). Maybe you can make it collapse into one of those "hamburger"-style buttons in those cases?

**Comment by simonmichael** [comment]
Great work @afh. This looks really nice when it works (on a big screen).

Unfortunately these home-grown CSS solutions are usually much more work than you think, to keep them working well across browsers, screen sizes etc. This one currently makes the site unreadable on a small screen (try "responsive design mode" or similar in your browser's dev tools). It also breaks Safari's reader mode, which shows the full page on the old site but is truncated on the new one.

Using a CSS framework or site generator (mdbook, mkdocs are two modern ones) usually solves this, at the cost of new complexity and maintenance work and a bit of "cookie cutter" sameness...

**Review by simonmichael — CHANGES_REQUESTED** [review]
General feedback @ https://github.com/ledger/ledger.github.io/pull/74#issuecomment-1518029469

**Comment by afh** [comment]
Thank you for the helpful feedback @kljohann and @simonmichael. I was so excited about the possibility of making the texinfo html a bit more modern, that I forgot about narrow screen devices. Apologies

This is addressed in e139aed1f3cdeb47a98e68afbdb43a2f68506c9c and the live preview has been updated accordingly.

@kljohann Making the navigation sidebar user togglable would likely require at JS and possibly a change of the DOM, two things that I'd like to avoid; my goal was to make the changes as minimally invasive as possible.

I wasn't aware that the CSS would affect Safari Reader mode in this way :/ Not sure how this could be addressed. Any of you have any ideas?

**Comment by afh** [comment]
Somewhat related: The GNU project provides CSS to style texinfo manuals.

Here's the Ledger manual with those styles applied: https://projects.surryhill.net/ledger/ledger3-with-gnu-css.html

While it is only a one line change, these styles do not support Dark Mode.

What are your thoughts on this?

**Comment by jwiegley** [comment]
Looks good to me, it's ok that it doesn't have dark mode; lots of browsers can force that anyway.

**Comment by afh** [comment]
Glad to hear it looks good to your, @jwiegley. I went ahead and created #75.

**Comment by afh** [comment]
Please hold for now.

**Comment by afh** [comment]
Closing as this surely was an entertaining and somewhat promising experiment a more thorough solution should ideally find its way to texinfo. Thanks for the helpful feedback all.

**Pull request closed without merging**
